export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILIURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAILIURE = "AUTH_LOGOUT_FAILURE";




export const GAME_LIST = "GAME_LIST";
export const GAME_LIST_SUCCESS = "GAME_LIST_SUCCESS";
export const GAME_LIST_FAILURE = "GAME_LIST_FAILURE";


export const GAME_STAR = "GAME_STAR";
export const GAME_STAR_SUCCESS = "GAME_STAR_SUCCESS";
export const GAME_STAR_FAILURE = "GAME_STAR_FAILURE";

export const GAME_LIST_RESET_SUCCESS = "GAME_LIST_RESET_SUCCESS";

export const GAME_SEARCH = "GAME_SEARCH";
export const GAME_SEARCH_SUCCESS = "GAME_SEARCH_SUCCESS";
export const GAME_SEARCH_FALSE = "GAME_SEARCH_FAILURE";
export const GAME_SEARCH_RESET_SUCCESS="GAME_SEARCH_RESET_SUCCESS";

export const MY_GAME = "MY_GAME";
export const MY_GAME_SUCCESS = "MY_GAME_SUCCESS";
export const MY_GAME_FALSE = "MY_GAME_FAILURE";
export const MY_GAME_RESET_SUCCESS="MY_GAME_RESET_SUCCESS";
